Add setSilent() method to URI class
bcit-ci/CodeIgniter4 pull request #3000
Opened 2020-05-15 17:47 UTC by michalsn

**Description**
Using `$uri->setSilent()` method will disable throwing exceptions. May be handy for using with methods like `getSegment()`.

Ref: #2952, #2949

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

2020-05-15 20:17 UTC, jreklund requested changes
Looks good, but I think we should reference it as $uri instead.

2020-05-15 20:17 UTC, jreklund commented on user_guide_src/source/libraries/uri.rst
> +	$request->setSilent();
Should be $uri->setSilent();

2020-05-15 20:17 UTC, jreklund commented on user_guide_src/source/libraries/uri.rst
> +	$request->setSilent(false);
Should be $uri->setSilent(false);

2020-05-15 20:33 UTC, michalsn commented on user_guide_src/source/libraries/uri.rst
> +	$request->setSilent();
Thanks.

2020-05-15 20:33 UTC, michalsn commented on user_guide_src/source/libraries/uri.rst
> +	$request->setSilent(false);
Done.

2020-05-16 11:14 UTC, michalsn commented
Oh great... now it not mergeable... I wonder what went wrong.

2020-05-16 16:05 UTC, michalsn commented
I don't know how to resolve this, so I'm closing this PR in favor of a new one: #3005

2020-05-16 16:05 UTC, closed without merging