Fix routes options to be recognizable via used HTTP request method
bcit-ci/CodeIgniter4 pull request #3751
Opened 2020-10-10 11:07 UTC by michalsn

**Description**
This PR fixes routes options to be recognizable via used HTTP request method. Right now routes options are shared - one instance per route. It leads to problems like: wrong named route name returned or firing incorrect filter.

I don't think this will introduce any BC, rather will fix buggy behavior, but if anyone notices the problem please let me know.

Fixes #3700 #3733

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] N/A User guide updated
- [x] Conforms to style guide

2020-10-10 11:17 UTC, samsonasik commented on system/Router/RouteCollection.php
> +	 * @param string $verb
```suggestion
       * @param string|null $verb
```

2020-10-10 11:17 UTC, samsonasik commented on system/Router/RouteCollection.php
> +	 * @param string $verb
```suggestion
       * @param string|null $verb
```

2020-10-10 11:17 UTC, samsonasik commented on system/Router/RouteCollection.php
> +	 * @param string $verb
```suggestion
       * @param string|null $verb
```

2020-10-10 11:17 UTC, samsonasik commented on system/Router/RouteCollection.php
> +	 * @param string $verb
```suggestion
       * @param string|null $verb
```

2020-10-10 11:58 UTC, MGatner requested changes
I like this. I agree with @samsonasik's changes, also... I know `getRoutes()` has an unspecified variable type on `$verb` but other things will break if it is not `string|null` so I think we should go ahead and update the function declaration to be consistent.

2020-10-10 12:16 UTC, paulbalandan commented on system/Router/RouteCollection.php
> +		}
```suggestion
	$verb = $verb ?: $this->getHTTPVerb();
```

2020-10-10 12:54 UTC, michalsn commented
Thanks for your code suggestions guys.

2020-10-11 12:35 UTC, MGatner approved these changes

2020-10-11 12:36 UTC, merged

2020-10-12 06:23 UTC, element-code commented
👍 i was writing a bug report just at this moment and saw the merge while digging for the buggy code 🎆