Language: Make production error message translatable
bcit-ci/CodeIgniter4 pull request #6197
Opened 2022-06-28 12:45 UTC by sba

With this pull request the error message in the file `app/Views/errors/html/production.php` can be translated.

I have named the file Errors.php because the translation of `app/Views/errors/html/error_exception.php` could also be added later.

2022-06-29 01:57 UTC, kenjis commented
Thank you for sending a PR.

You must [GPG-sign](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/signing.md) your work, certifying that you either wrote the work or otherwise have the right to pass it on to an open-source project. See [Developer's Certificate of Origin](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/DCO.md).
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

2022-06-29 01:58 UTC, kenjis commented on app/Views/errors/html/production.php
> +    <title><?= lang('Errors.whoops')?></title>
```suggestion
    <title><?= lang('Errors.whoops') ?></title>
```

2022-06-29 01:58 UTC, kenjis commented on app/Views/errors/html/production.php
> +        <h1 class="headline"><?= lang('Errors.whoops')?></h1>
```suggestion
        <h1 class="headline"><?= lang('Errors.whoops') ?></h1>
```

2022-06-29 01:58 UTC, kenjis commented on app/Views/errors/html/production.php
> +        <p class="lead"><?= lang('Errors.weHitASnag')?></p>
```suggestion
        <p class="lead"><?= lang('Errors.weHitASnag') ?></p>
```

2022-06-29 08:10 UTC, sba commented
Hi @kenjis 
Thanks for checking my PR and the GPG links. I will try to GPG-sign my commit...never did this before. Should I close this PR and make a new, signed one?
And is the naming "Errors.php" acceptable or do you have a better suggestion?
I thought about another name in case welcome_message.php should be made translatable later - but I think it would be better to name it for this Welcome.php anyway.

2022-06-29 08:30 UTC, kenjis commented
> Should I close this PR and make a new, signed one?

No. You can do `git commit --amend`, and force push.

2022-06-29 10:30 UTC, kenjis commented
Agreed. It seems better to go to 4.3.

2022-06-29 12:07 UTC, sba commented
> 2. The new language file will require adoption by the translations repo before this will actually work.

I will have a look to the translations repo and try to update the necessary things (tests etc.)

2022-06-30 10:29 UTC, MGatner commented
Thanks @sba. To clarify, this should work fine without the translations (it falls back to English), but any additions you can make to the translations repo to go along with it would be appreciated!

2022-07-01 11:25 UTC, ddevsr commented
With this PR, must include in :
https://github.com/codeigniter4/CodeIgniter4/blob/develop/app/Views/errors/html/error_404.php#L79

**Sorry! Cannot seem to find the page you were looking for.** can multilingual too

2022-07-05 09:08 UTC, kenjis requested changes
This should go to 4.3 branch. Please change the base branch.

2022-07-05 09:30 UTC, kenjis approved these changes
LGTM!

2022-07-05 09:32 UTC, kenjis commented
@sba You forgot to sign your commits.
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

2022-07-05 10:08 UTC, sba commented
> @sba You forgot to sign your commits. See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#signing

Yes, I know, sorry! It's a crap, I've wasted hours on it and signing still doesn't work...... I'll try again, sometime.

2022-07-05 10:52 UTC, MGatner approved these changes
Looks good! I like @ddevsr's suggestion to include the 404 error as well, but that could be a separate PR if you're done with this.

2022-07-05 21:41 UTC, kenjis requested changes
There are many unrelated commits.
Please drop these.

2022-07-05 21:48 UTC, kenjis commented
@sba Thank you for GPG signing.

But unfortunately this PR branch has many unrelated commits.
You need to clean up the branch.

I recommend you create a new branch from `4.3`, 
See https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#branching-revisited
and cherry-pick commits you made.
After that remove this  PR branch `develop`, and rename the new branch to `develop` and force push.

Or it is easier just to create another PR.

2022-07-06 05:43 UTC, closed without merging