docs: update return type
bcit-ci/CodeIgniter4 pull request #8709
Opened 2024-04-04 03:30 UTC by Pebryan354

**Description**
when I use the getRow function in the query builder 
`$this->db->table("table_name")->getWhere(["id" => $id])->getRow("name")`, it works fine, but there is a notif or warning "Expected type 'string'...."

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

2024-04-04 10:59 UTC, kenjis commented on system/Database/BaseResult.php
> +     * @return         array|object|stdClass|null|string
Oh, yes, `$n` might be a column name.
So the return value might be `int` or `float`.

2024-04-04 11:00 UTC, kenjis commented on system/Database/BaseResult.php
>       * @phpstan-return ($type is 'object' ? stdClass|null : ($type is 'array' ? array|null : T|null))
Can you also fix `@phpstan-return` ?

2024-04-04 11:17 UTC, kenjis commented
Please fix coding style. 
See https://github.com/codeigniter4/CodeIgniter4/actions/runs/8548870578/job/23436880333?pr=8709
and https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/pull_request.md#php-style

2024-04-05 04:03 UTC, Pebryan354 commented on system/Database/BaseResult.php
>       * @phpstan-return ($type is 'object' ? stdClass|null : ($type is 'array' ? array|null : T|null))
sorry I don't understand doing this

2024-04-05 06:33 UTC, michalsn approved these changes

2024-04-05 07:19 UTC, kenjis commented on system/Database/BaseResult.php
>       * @phpstan-return ($type is 'object' ? stdClass|null : ($type is 'array' ? array|null : T|null))
Okay.

```suggestion
     * @phpstan-return ($n is string ? float|int|string|null : ($type is 'object' ? stdClass|null : ($type is 'array' ? array|null : T|null)))
```
See https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types

2024-04-05 07:21 UTC, kenjis requested changes
Please update `ResultInterface`, too.
```diff
--- a/system/Database/ResultInterface.php
+++ b/system/Database/ResultInterface.php
@@ -63,8 +63,8 @@ interface ResultInterface
      * @param         string                           $type The type of result object. 'array', 'object' or class name.
      * @phpstan-param class-string<T>|'array'|'object' $type
      *
-     * @return         array|object|stdClass|null
-     * @phpstan-return ($type is 'object' ? stdClass|null : ($type is 'array' ? array|null : T|null))
+     * @return         array|float|int|object|stdClass|string|null
+     * @phpstan-return ($n is string ? float|int|string|null : ($type is 'object' ? stdClass|null : ($type is 'array' ? array|null : T|null)))
      */
     public function getRow($n = 0, string $type = 'object');
 
```

2024-04-05 07:51 UTC, totoprayogo1916 approved these changes

2024-04-05 08:25 UTC, kenjis approved these changes

2024-04-05 08:26 UTC, merged

2024-04-05 08:26 UTC, kenjis commented
@Pebryan354 Thank you!